import type { LabSpec } from "../spec/schema.js";

/**
 * A CONCEPT NODE.
 *
 * A node is where information about one concept lands — collected by a person, generated by the
 * LLM, or both — and the canvas compiles it into an interactive page. It is the unit of work: one
 * person owns a set of nodes, and each node stands up as its own lab.
 *
 * Distinct from a *renderer* (`src/canvas/renderers/*`), which is the machinery that draws. A node
 * names the renderer it wants; several nodes share one renderer.
 *
 * `spec` may be hand-authored (as B-tree and LinkedList are) or produced by the generator. Either
 * way it goes through `parseLabSpec` before it reaches the canvas, so a hand-authored node is held
 * to exactly the same bar as a generated one.
 */
export interface ConceptNode {
  /** URL slug: /node/<id> */
  id: string;
  title: string;
  /** Rough grouping, for the gallery. */
  domain: "cs" | "biology" | "physics" | "math" | "systems" | "finance" | "other";
  /** One line: what a learner walks away knowing. */
  summary: string;
  /**
   * The lab. Untyped because it is validated at load, exactly like model output — a node that
   * drifts out of schema should fail loudly at its own route, not render something subtly wrong.
   */
  spec: unknown;
  /**
   * Where the information came from, and what was deliberately left out. Kept with the node
   * because the next person to touch it needs the reasoning, not just the result.
   */
  notes?: string;
}

export type { LabSpec };
